{
 "title": "GreenDot Dashboard",
 "time": { "from": "2023-11-27T04:06:40.480Z", "to": "2023-11-27T16:06:40.480Z" },
 "panels": [
  {
   "title": "Probability",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", fire_probability AS node_0 FROM firecloud WHERE node_id = 0 LIMIT 50 "
    },
    {
     "rawSql": "SELECT \"timestamp\", fire_probability AS node_1 FROM firecloud WHERE node_id = 1 LIMIT 50 "
    }
   ]
  },
  { "title": "Node 0", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Probability of Fire",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  fire_probability,\n  timestamp\nFROM\n  firecloud\nORDER BY\n  timestamp DESC\nLIMIT\n  1\n"
    }
   ]
  },
  {
   "title": "Flame Sensor",
   "type": "stat",
   "description": "Current Flame Sensor Value",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n  flame_sensor_value\nfrom\n  firecloud\nwhere\n  node_id = 0\norder by\n  timestamp desc\nlimit\n  1;"
    }
   ]
  },
  {
   "title": "Air Quality Sensor",
   "type": "gauge",
   "description": "Current Presence of CO2 in Air (ppm)",
   "gridPos": { "h": 6, "w": 4, "x": 14, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n  air_quality_ppm\nfrom\n  firecloud\nwhere\n  node_id = 0\norder by\n  timestamp desc\nlimit\n  1;"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n  temperature\nfrom\n  firecloud\nwhere\n  node_id = 0\norder by\n  timestamp desc\nlimit\n  1;"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "description": "Current Humidity Level",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n  humidity\nfrom\n  firecloud\nwhere\n  node_id = 0\norder by\n  timestamp desc\nlimit\n  1;"
    }
   ]
  },
  {
   "title": "Temperature & Humidity R-value",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n  r_value\nfrom\n  firecloud\nwhere\n  node_id = 0\norder by\n  timestamp desc\nlimit\n  1;"
    }
   ]
  }
 ]
}